// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://exdszczkyijgsqpgbvsp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV4ZHN6Y3preWlqZ3NxcGdidnNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEzMjQyMzEsImV4cCI6MjA3NjkwMDIzMX0.kbP56L2Zt6gaJWs_fRxuvug1_mChNyOC0cJ3clJOdKo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});